#!/usr/bin/env bash
#
# Build and install capstone from source
#
# Instructions: https://github.com/capstone-engine/capstone/blob/4.0.2/COMPILE.TXT
#

function usage() {
    echo "Usage: $(basename $0) <install_dir>"
}

function _install_here() {
    local install_dir="$1"
    local make_jobs="1"

    # Auto-detect running in a slurm job and use multiple processes to build
    if [ -z $SCONS_EXTRA_ARGS ] && [ ! -z $SLURM_JOB_NUM_NODES  ]; then
        make_jobs=$(scontrol show node $(hostname | cut -d "." -f 1) | grep -o "CPUAlloc=[0-9]\+" | grep -o "[0-9]\+")
        make_jobs=$(( $build_cores - 4 ))
        echo "Detecting running in slurm. Building with MAKE_JOBS=${make_jobs}"
    fi

    wget https://github.com/capstone-engine/capstone/archive/refs/tags/4.0.2.tar.gz || return
    tar -xvzf 4.0.2.tar.gz || return
    pushd capstone-4.0.2
        mkdir -p "$install_dir" || return
        CAPSTONE_ARCHS="x86" ./make.sh
        MAKE_JOBS="$make_jobs" PREFIX="$install_dir" ./make.sh install
    popd
}

function install() {
    local install_dir="$1"
    local rc=0

    echo "Installing capstone in $install_dir"
    tmp_dir="$(mktemp -d 2>/dev/null)"
    pushd "$tmp_dir"
        _install_here "$install_dir"
        rc=$?
    popd
    rm -r "$tmp_dir"
    if [ $rc == 0 ]; then
        echo "Success!"
    fi
    exit $rc
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

install "$1"

