#!/usr/bin/env bash
#
# Build and install cmocka from scratch
#
# Source: https://github.com/clibs/cmocka/blob/master/INSTALL.md
#

function usage() {
    echo "Usage: $(basename $0) <install_dir>"
}

function _install_here() {
    local install_dir="$1"

    wget https://cmocka.org/files/1.1/cmocka-1.1.7.tar.xz || return
    tar xvf cmocka-1.1.7.tar.xz || return
    pushd cmocka-1.1.7
      mkdir build
      pushd build
        cmake -DCMAKE_INSTALL_PREFIX=${install_dir} .. || return
        make || return
        make install || return

        popd
    popd
}

function install() {
    local install_dir="$1"
    local rc=0

    echo "Installing cmocka in $install_dir"
    tmp_dir="$(mktemp -d 2>/dev/null)"
    pushd "$tmp_dir"
        _install_here "$install_dir"
        rc=$?
    popd
    rm -r "$tmp_dir"
    if [ $rc == 0 ]; then
        echo "Success!"
    fi
    exit $rc
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

install "$1"

