#
# Standard Frontera environment for the test runner and client execution.
#

DAOS_DIR=$1

# Unused Frontera modules
# TODO purge and load only what we need?
module unload impi pmix hwloc intel

export FI_UNIVERSE_SIZE=16383
export FI_OFI_RXM_USE_SRX=1
export D_LOG_FILE=/tmp/daos_logs/daos_client.log
export D_LOG_MASK=ERR
export CRT_PHY_ADDR_STR="ofi+verbs;ofi_rxm"
export OFI_INTERFACE=ib0
export OFI_DOMAIN=mlx5_0
export DAOS_AGENT_DRPC_DIR=/tmp/daos_agent
export DAOS_DISABLE_REQ_FWD=1

DAOS_INSTALL_PATH=$DAOS_DIR/install
DAOS_PREREQ_PATH=$DAOS_INSTALL_PATH/prereq/release

PATH=${DAOS_PREREQ_PATH}/argobots/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/isal/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/isal_crypto/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/mercury/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/ofi/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/openpa/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/pmdk/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/protobufc/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/psm2/bin:$PATH
PATH=${DAOS_PREREQ_PATH}/spdk/bin:$PATH

PATH=~/.local/bin:$PATH
PATH=${DAOS_INSTALL_PATH}/bin/:$PATH
PATH=${DAOS_INSTALL_PATH}/sbin/:$PATH

LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/argobots/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/isal/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/isal_crypto/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/mercury/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/ofi/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/openpa/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/pmdk/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/protobufc/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/psm2/lib64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_PREREQ_PATH}/spdk/lib:$LD_LIBRARY_PATH

LD_LIBRARY_PATH=${DAOS_INSTALL_PATH}/lib64/:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_INSTALL_PATH}/lib64/daos_srv/:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${DAOS_INSTALL_PATH}/lib/:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/

CPATH=${DAOS_INSTALL_PATH}/include/:$CPATH

PYTHONPATH=$DAOS_INSTALL_DIR/lib/daos/TESTING/ftest/util:$PYTHONPATH
PYTHONPATH=$DAOS_INSTALL_DIR/lib/daos/TESTING/ftest/util/apricot:$PYTHONPATH
PYTHONPATH=$DAOS_INSTALL_PATH/lib64/python3/site-packages:$PYTHONPATH
PYTHONPATH=$PYTHONPATH:~/.local/lib

export PATH LD_LIBRARY_PATH CPATH PYTHONPATH
