#!/bin/bash

DATASET_SIZE=500
IOR_BLOCK_SIZE=47008
IOR_OPTS="$IOR_OPTS -t $IOR_BLOCK_SIZE -b $IOR_BLOCK_SIZE -C -Q 1 -g -G 27 -e --dfs.chunk_size=470080"
DAOS_CONTAINER_EXTRA_PROPERTIES=ec_cell_sz:$IOR_BLOCK_SIZE
